server:
  port: 3033


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    instance-id: "match-service"
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
    register-with-eureka: true
    fetch-registry: true


spring:
  cloud:
    client:
      hostname : match-service
  application:
    name: match-service

management:
  security:
    enabled: false

logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG