server:
  port: ${PORT:8761}

eureka:

  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    fetch-registry: false
  instance:
    leaseRenewalIntervalInSeconds: 10

management:
  security:
    enabled: false
spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin  #A different context path for admin server has been provided not conflicting with eureka